# Generated by Django 2.1.4 on 2019-01-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vis', '0002_texture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Texture',
        ),
    ]
